import type { Metadata } from 'next' 
//import '/styles/styles.scss'; 
import './globals.css'
import { Header } from '../components/Header';

export const metadata: Metadata = {
  title: 'Tab Roller',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Header />  
        {children}
      </body>
    </html>
  )
}
